import { HeroSection } from './Hero.styled';

const Hero = () => {
  return (
    <HeroSection>
      <h1>
        a Story that started with <span>one simple ape</span>
      </h1>
      <p>
        WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
        IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
      </p>
      <button>svg</button>
      <p>
        EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
        RANDOMLY GENERATED BY USERS
      </p>
      <img />
    </HeroSection>
  );
};

export default Hero;
