import { AboutSection } from './About.styled';
import ape from 'img/AboutApe-mobile.png';
import { ReactComponent as Cross } from '../../img/cross.svg';
import Banner from './Banner/Banner';

const About = () => {
  return (
    <>
      <AboutSection>
        <h1>
          a Story that started with <span>one simple ape</span>
        </h1>
        <p>
          WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
          IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
        </p>
        <Cross />
        <p>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </p>
        <img src={ape} alt="Hero Ape" />
      </AboutSection>
      <Banner />
    </>
  );
};

export default About;
